tasks:
- command: >
    sudo apt-get update && 
    sudo apt-get install libseccomp-dev -y && 
    sudo apt-get install strace -y &&
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rust_install.sh && 
    /bin/sh rust_install.sh -y && 
    rm rust_install.sh && 
    rustup install 1.58 &&
    rustup default 1.58
