name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y libseccomp-dev protobuf-compiler && >
          git submodule sync test-collection
      - name: Test Command sh
        run: sh -c "echo test"
      - name: Check ENV
        run: echo $(rustup --version && gcc -v)
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
