name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libseccomp-dev
      run: sudo apt-get install libseccomp-dev
    - name: Build
      run: sudo cargo build --verbose
    - name: Run tests
      run: sudo cargo test --verbose
