name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get install -y libseccomp-dev protobuf-compiler g++-11
      - name: Setup g++-11
        run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
      - name: Check ENV
        run: echo $(rustup --version && g++ -v)
      - name: Build test dist
        run: cd test-collection && ./build.sh && cd ..
      - name: Run tests
        run: RUST_LOG=info cargo test --verbose -- --nocapture
